* Refresh patches, sorting files in each patch.

diff --git a/debian/patches/pgo+lto-3.diff b/debian/patches/pgo+lto-3.diff
--- a/debian/patches/pgo+lto-3.diff
+++ b/debian/patches/pgo+lto-3.diff
@@ -42,186 +42,6 @@ NB: --enable-pgo-build=lto enables the PGO build with LTO while
  configure.ac |  65 +++++++++++++++++++++++++++++++++
  4 files changed, 279 insertions(+), 6 deletions(-)
 
---- a/Makefile.in
-+++ b/Makefile.in
-@@ -412,6 +412,48 @@ CXXFLAGS = @CXXFLAGS@
- LIBCXXFLAGS = $(CXXFLAGS) -fno-implicit-templates
- GOCFLAGS = $(CFLAGS)
- 
-+# Pass additional PGO and LTO compiler options to the PGO build.
-+BUILD_CFLAGS = $(PGO_BUILD_CFLAGS) $(PGO_BUILD_LTO_CFLAGS)
-+override CFLAGS += $(BUILD_CFLAGS)
-+override CXXFLAGS += $(BUILD_CFLAGS)
-+
-+# Additional PGO and LTO compiler options to generate profiling data
-+# for the PGO build.
-+PGO_BUILD_GEN_FLAGS_TO_PASS = \
-+	PGO_BUILD_CFLAGS="@PGO_BUILD_GEN_CFLAGS@" \
-+	PGO_BUILD_LTO_CFLAGS="@PGO_BUILD_LTO_CFLAGS@"
-+
-+# NB: Filter out any compiler options which may fail PGO training runs.
-+PGO_BUILD_TRAINING_CFLAGS:= \
-+	$(filter-out -Werror=%,$(CFLAGS))
-+PGO_BUILD_TRAINING_CXXFLAGS:=\
-+	$(filter-out -Werror=%,$(CXXFLAGS))
-+PGO_BUILD_TRAINING_CFLAGS:= \
-+	$(filter-out -Wall,$(PGO_BUILD_TRAINING_CFLAGS))
-+PGO_BUILD_TRAINING_CXXFLAGS:= \
-+	$(filter-out -Wall,$(PGO_BUILD_TRAINING_CXXFLAGS))
-+PGO_BUILD_TRAINING_CFLAGS:= \
-+	$(filter-out -specs=%,$(PGO_BUILD_TRAINING_CFLAGS))
-+PGO_BUILD_TRAINING_CXXFLAGS:= \
-+	$(filter-out -specs=%,$(PGO_BUILD_TRAINING_CXXFLAGS))
-+PGO_BUILD_TRAINING_FLAGS_TO_PASS = \
-+	CFLAGS_FOR_TARGET="$(PGO_BUILD_TRAINING_CFLAGS)" \
-+	CXXFLAGS_FOR_TARGET="$(PGO_BUILD_TRAINING_CXXFLAGS)"
-+
-+# Ignore "make check" errors in PGO training runs.
-+PGO_BUILD_TRAINING_MFLAGS = -i
-+
-+# Additional PGO and LTO compiler options to use profiling data for the
-+# PGO build.
-+PGO_BUILD_USE_FLAGS_TO_PASS = \
-+	PGO_BUILD_CFLAGS="@PGO_BUILD_USE_CFLAGS@" \
-+	PGO_BUILD_LTO_CFLAGS="@PGO_BUILD_LTO_CFLAGS@"
-+
-+# PGO training targets for the PGO build.  FIXME: Add gold tests to
-+# training.
-+PGO-TRAINING-TARGETS = binutils gas gdb ld sim
-+PGO_BUILD_TRAINING = $(addprefix maybe-check-,$(PGO-TRAINING-TARGETS))
-+
- CREATE_GCOV = create_gcov
- 
- TFLAGS =
-@@ -985,6 +1027,12 @@ configure-target:  \
- 
- # The target built for a native non-bootstrap build.
- .PHONY: all
-+
-+# --enable-pgo-build enables the PGO build.
-+# 1. First build with -fprofile-generate.
-+# 2. Use "make maybe-check-*" to generate profiling data.
-+# 3. Use "make clean" to remove the previous build.
-+# 4. Rebuild with -fprofile-use.
- all:
- @if gcc-bootstrap
- 	[ -f stage_final ] || echo stage3 > stage_final
-@@ -993,7 +1041,7 @@ all:
- 	$(MAKE) $(RECURSE_FLAGS_TO_PASS) `cat stage_final`-bubble
- @endif gcc-bootstrap
- 	@: $(MAKE); $(unstage)
--	@r=`${PWD_COMMAND}`; export r; \
-+	+@r=`${PWD_COMMAND}`; export r; \
- 	s=`cd $(srcdir); ${PWD_COMMAND}`; export s; \
- @if gcc-bootstrap
- 	if [ -f stage_last ]; then \
-@@ -1001,7 +1049,17 @@ all:
- 	  $(MAKE) $(TARGET_FLAGS_TO_PASS) all-host all-target; \
- 	else \
- @endif gcc-bootstrap
--	  $(MAKE) $(RECURSE_FLAGS_TO_PASS) all-host all-target \
-+	  $(MAKE) $(RECURSE_FLAGS_TO_PASS) \
-+		$(PGO_BUILD_GEN_FLAGS_TO_PASS) all-host all-target \
-+@if pgo-build
-+	&& $(MAKE) $(RECURSE_FLAGS_TO_PASS) \
-+		$(PGO_BUILD_TRAINING_MFLAGS) \
-+		$(PGO_BUILD_TRAINING_FLAGS_TO_PASS) \
-+		$(PGO_BUILD_TRAINING) \
-+	&& $(MAKE) $(RECURSE_FLAGS_TO_PASS) clean \
-+	&& $(MAKE) $(RECURSE_FLAGS_TO_PASS) \
-+		$(PGO_BUILD_USE_FLAGS_TO_PASS) all-host all-target \
-+@endif pgo-build
- @if gcc-bootstrap
- 	    ; \
- 	fi \
---- a/Makefile.tpl
-+++ b/Makefile.tpl
-@@ -415,6 +415,45 @@ CXXFLAGS = @CXXFLAGS@
- LIBCXXFLAGS = $(CXXFLAGS) -fno-implicit-templates
- GOCFLAGS = $(CFLAGS)
- 
-+# Pass additional PGO and LTO compiler options to the PGO build.
-+BUILD_CFLAGS = $(PGO_BUILD_CFLAGS) $(PGO_BUILD_LTO_CFLAGS)
-+override CFLAGS += $(BUILD_CFLAGS)
-+override CXXFLAGS += $(BUILD_CFLAGS)
-+
-+# Additional PGO and LTO compiler options to generate profiling data
-+# for the PGO build.
-+PGO_BUILD_GEN_FLAGS_TO_PASS = \
-+	PGO_BUILD_CFLAGS="@PGO_BUILD_GEN_CFLAGS@" \
-+	PGO_BUILD_LTO_CFLAGS="@PGO_BUILD_LTO_CFLAGS@"
-+
-+# NB: Filter out any compiler options which may fail PGO training runs.
-+PGO_BUILD_TRAINING_CFLAGS:= \
-+	$(filter-out -Werror=%,$(CFLAGS))
-+PGO_BUILD_TRAINING_CXXFLAGS:=\
-+	$(filter-out -Werror=%,$(CXXFLAGS))
-+PGO_BUILD_TRAINING_CFLAGS:= \
-+	$(filter-out -Wall,$(PGO_BUILD_TRAINING_CFLAGS))
-+PGO_BUILD_TRAINING_CXXFLAGS:= \
-+	$(filter-out -Wall,$(PGO_BUILD_TRAINING_CXXFLAGS))
-+PGO_BUILD_TRAINING_CFLAGS:= \
-+	$(filter-out -specs=%,$(PGO_BUILD_TRAINING_CFLAGS))
-+PGO_BUILD_TRAINING_CXXFLAGS:= \
-+	$(filter-out -specs=%,$(PGO_BUILD_TRAINING_CXXFLAGS))
-+PGO_BUILD_TRAINING_FLAGS_TO_PASS = \
-+	CFLAGS_FOR_TARGET="$(PGO_BUILD_TRAINING_CFLAGS)" \
-+	CXXFLAGS_FOR_TARGET="$(PGO_BUILD_TRAINING_CXXFLAGS)"
-+
-+# Additional PGO and LTO compiler options to use profiling data for the
-+# PGO build.
-+PGO_BUILD_USE_FLAGS_TO_PASS = \
-+	PGO_BUILD_CFLAGS="@PGO_BUILD_USE_CFLAGS@" \
-+	PGO_BUILD_LTO_CFLAGS="@PGO_BUILD_LTO_CFLAGS@"
-+
-+# PGO training targets for the PGO build.  FIXME: Add gold tests to
-+# training.
-+PGO-TRAINING-TARGETS = binutils gas gdb ld sim
-+PGO_BUILD_TRAINING = $(addprefix maybe-check-,$(PGO-TRAINING-TARGETS))
-+
- CREATE_GCOV = create_gcov
- 
- TFLAGS =
-@@ -719,6 +758,12 @@ configure-target: [+
- 
- # The target built for a native non-bootstrap build.
- .PHONY: all
-+
-+# --enable-pgo-build enables the PGO build.
-+# 1. First build with -fprofile-generate.
-+# 2. Use "make maybe-check-*" to generate profiling data.
-+# 3. Use "make clean" to remove the previous build.
-+# 4. Rebuild with -fprofile-use.
- all:
- @if gcc-bootstrap
- 	[ -f stage_final ] || echo stage3 > stage_final
-@@ -727,7 +772,7 @@ all:
- 	$(MAKE) $(RECURSE_FLAGS_TO_PASS) `cat stage_final`-bubble
- @endif gcc-bootstrap
- 	@: $(MAKE); $(unstage)
--	@r=`${PWD_COMMAND}`; export r; \
-+	+@r=`${PWD_COMMAND}`; export r; \
- 	s=`cd $(srcdir); ${PWD_COMMAND}`; export s; \
- @if gcc-bootstrap
- 	if [ -f stage_last ]; then \
-@@ -735,7 +780,16 @@ all:
- 	  $(MAKE) $(TARGET_FLAGS_TO_PASS) all-host all-target; \
- 	else \
- @endif gcc-bootstrap
--	  $(MAKE) $(RECURSE_FLAGS_TO_PASS) all-host all-target \
-+	  $(MAKE) $(RECURSE_FLAGS_TO_PASS) \
-+		$(PGO_BUILD_GEN_FLAGS_TO_PASS) all-host all-target \
-+@if pgo-build
-+	&& $(MAKE) $(RECURSE_FLAGS_TO_PASS) \
-+		$(PGO_BUILD_TRAINING_FLAGS_TO_PASS) \
-+		$(PGO_BUILD_TRAINING) \
-+	&& $(MAKE) $(RECURSE_FLAGS_TO_PASS) clean \
-+	&& $(MAKE) $(RECURSE_FLAGS_TO_PASS) \
-+		$(PGO_BUILD_USE_FLAGS_TO_PASS) all-host all-target \
-+@endif pgo-build
- @if gcc-bootstrap
- 	    ; \
- 	fi \
 --- a/configure
 +++ b/configure
 @@ -692,6 +692,9 @@ extra_mpc_gmp_configure_flags
@@ -447,3 +267,183 @@ NB: --enable-pgo-build=lto enables the PGO build with LTO while
  # Create the serialization dependencies.  This uses a temporary file.
  
  AC_ARG_ENABLE([serial-configure],
+--- a/Makefile.in
++++ b/Makefile.in
+@@ -412,6 +412,48 @@ CXXFLAGS = @CXXFLAGS@
+ LIBCXXFLAGS = $(CXXFLAGS) -fno-implicit-templates
+ GOCFLAGS = $(CFLAGS)
+ 
++# Pass additional PGO and LTO compiler options to the PGO build.
++BUILD_CFLAGS = $(PGO_BUILD_CFLAGS) $(PGO_BUILD_LTO_CFLAGS)
++override CFLAGS += $(BUILD_CFLAGS)
++override CXXFLAGS += $(BUILD_CFLAGS)
++
++# Additional PGO and LTO compiler options to generate profiling data
++# for the PGO build.
++PGO_BUILD_GEN_FLAGS_TO_PASS = \
++	PGO_BUILD_CFLAGS="@PGO_BUILD_GEN_CFLAGS@" \
++	PGO_BUILD_LTO_CFLAGS="@PGO_BUILD_LTO_CFLAGS@"
++
++# NB: Filter out any compiler options which may fail PGO training runs.
++PGO_BUILD_TRAINING_CFLAGS:= \
++	$(filter-out -Werror=%,$(CFLAGS))
++PGO_BUILD_TRAINING_CXXFLAGS:=\
++	$(filter-out -Werror=%,$(CXXFLAGS))
++PGO_BUILD_TRAINING_CFLAGS:= \
++	$(filter-out -Wall,$(PGO_BUILD_TRAINING_CFLAGS))
++PGO_BUILD_TRAINING_CXXFLAGS:= \
++	$(filter-out -Wall,$(PGO_BUILD_TRAINING_CXXFLAGS))
++PGO_BUILD_TRAINING_CFLAGS:= \
++	$(filter-out -specs=%,$(PGO_BUILD_TRAINING_CFLAGS))
++PGO_BUILD_TRAINING_CXXFLAGS:= \
++	$(filter-out -specs=%,$(PGO_BUILD_TRAINING_CXXFLAGS))
++PGO_BUILD_TRAINING_FLAGS_TO_PASS = \
++	CFLAGS_FOR_TARGET="$(PGO_BUILD_TRAINING_CFLAGS)" \
++	CXXFLAGS_FOR_TARGET="$(PGO_BUILD_TRAINING_CXXFLAGS)"
++
++# Ignore "make check" errors in PGO training runs.
++PGO_BUILD_TRAINING_MFLAGS = -i
++
++# Additional PGO and LTO compiler options to use profiling data for the
++# PGO build.
++PGO_BUILD_USE_FLAGS_TO_PASS = \
++	PGO_BUILD_CFLAGS="@PGO_BUILD_USE_CFLAGS@" \
++	PGO_BUILD_LTO_CFLAGS="@PGO_BUILD_LTO_CFLAGS@"
++
++# PGO training targets for the PGO build.  FIXME: Add gold tests to
++# training.
++PGO-TRAINING-TARGETS = binutils gas gdb ld sim
++PGO_BUILD_TRAINING = $(addprefix maybe-check-,$(PGO-TRAINING-TARGETS))
++
+ CREATE_GCOV = create_gcov
+ 
+ TFLAGS =
+@@ -985,6 +1027,12 @@ configure-target:  \
+ 
+ # The target built for a native non-bootstrap build.
+ .PHONY: all
++
++# --enable-pgo-build enables the PGO build.
++# 1. First build with -fprofile-generate.
++# 2. Use "make maybe-check-*" to generate profiling data.
++# 3. Use "make clean" to remove the previous build.
++# 4. Rebuild with -fprofile-use.
+ all:
+ @if gcc-bootstrap
+ 	[ -f stage_final ] || echo stage3 > stage_final
+@@ -993,7 +1041,7 @@ all:
+ 	$(MAKE) $(RECURSE_FLAGS_TO_PASS) `cat stage_final`-bubble
+ @endif gcc-bootstrap
+ 	@: $(MAKE); $(unstage)
+-	@r=`${PWD_COMMAND}`; export r; \
++	+@r=`${PWD_COMMAND}`; export r; \
+ 	s=`cd $(srcdir); ${PWD_COMMAND}`; export s; \
+ @if gcc-bootstrap
+ 	if [ -f stage_last ]; then \
+@@ -1001,7 +1049,17 @@ all:
+ 	  $(MAKE) $(TARGET_FLAGS_TO_PASS) all-host all-target; \
+ 	else \
+ @endif gcc-bootstrap
+-	  $(MAKE) $(RECURSE_FLAGS_TO_PASS) all-host all-target \
++	  $(MAKE) $(RECURSE_FLAGS_TO_PASS) \
++		$(PGO_BUILD_GEN_FLAGS_TO_PASS) all-host all-target \
++@if pgo-build
++	&& $(MAKE) $(RECURSE_FLAGS_TO_PASS) \
++		$(PGO_BUILD_TRAINING_MFLAGS) \
++		$(PGO_BUILD_TRAINING_FLAGS_TO_PASS) \
++		$(PGO_BUILD_TRAINING) \
++	&& $(MAKE) $(RECURSE_FLAGS_TO_PASS) clean \
++	&& $(MAKE) $(RECURSE_FLAGS_TO_PASS) \
++		$(PGO_BUILD_USE_FLAGS_TO_PASS) all-host all-target \
++@endif pgo-build
+ @if gcc-bootstrap
+ 	    ; \
+ 	fi \
+--- a/Makefile.tpl
++++ b/Makefile.tpl
+@@ -415,6 +415,45 @@ CXXFLAGS = @CXXFLAGS@
+ LIBCXXFLAGS = $(CXXFLAGS) -fno-implicit-templates
+ GOCFLAGS = $(CFLAGS)
+ 
++# Pass additional PGO and LTO compiler options to the PGO build.
++BUILD_CFLAGS = $(PGO_BUILD_CFLAGS) $(PGO_BUILD_LTO_CFLAGS)
++override CFLAGS += $(BUILD_CFLAGS)
++override CXXFLAGS += $(BUILD_CFLAGS)
++
++# Additional PGO and LTO compiler options to generate profiling data
++# for the PGO build.
++PGO_BUILD_GEN_FLAGS_TO_PASS = \
++	PGO_BUILD_CFLAGS="@PGO_BUILD_GEN_CFLAGS@" \
++	PGO_BUILD_LTO_CFLAGS="@PGO_BUILD_LTO_CFLAGS@"
++
++# NB: Filter out any compiler options which may fail PGO training runs.
++PGO_BUILD_TRAINING_CFLAGS:= \
++	$(filter-out -Werror=%,$(CFLAGS))
++PGO_BUILD_TRAINING_CXXFLAGS:=\
++	$(filter-out -Werror=%,$(CXXFLAGS))
++PGO_BUILD_TRAINING_CFLAGS:= \
++	$(filter-out -Wall,$(PGO_BUILD_TRAINING_CFLAGS))
++PGO_BUILD_TRAINING_CXXFLAGS:= \
++	$(filter-out -Wall,$(PGO_BUILD_TRAINING_CXXFLAGS))
++PGO_BUILD_TRAINING_CFLAGS:= \
++	$(filter-out -specs=%,$(PGO_BUILD_TRAINING_CFLAGS))
++PGO_BUILD_TRAINING_CXXFLAGS:= \
++	$(filter-out -specs=%,$(PGO_BUILD_TRAINING_CXXFLAGS))
++PGO_BUILD_TRAINING_FLAGS_TO_PASS = \
++	CFLAGS_FOR_TARGET="$(PGO_BUILD_TRAINING_CFLAGS)" \
++	CXXFLAGS_FOR_TARGET="$(PGO_BUILD_TRAINING_CXXFLAGS)"
++
++# Additional PGO and LTO compiler options to use profiling data for the
++# PGO build.
++PGO_BUILD_USE_FLAGS_TO_PASS = \
++	PGO_BUILD_CFLAGS="@PGO_BUILD_USE_CFLAGS@" \
++	PGO_BUILD_LTO_CFLAGS="@PGO_BUILD_LTO_CFLAGS@"
++
++# PGO training targets for the PGO build.  FIXME: Add gold tests to
++# training.
++PGO-TRAINING-TARGETS = binutils gas gdb ld sim
++PGO_BUILD_TRAINING = $(addprefix maybe-check-,$(PGO-TRAINING-TARGETS))
++
+ CREATE_GCOV = create_gcov
+ 
+ TFLAGS =
+@@ -719,6 +758,12 @@ configure-target: [+
+ 
+ # The target built for a native non-bootstrap build.
+ .PHONY: all
++
++# --enable-pgo-build enables the PGO build.
++# 1. First build with -fprofile-generate.
++# 2. Use "make maybe-check-*" to generate profiling data.
++# 3. Use "make clean" to remove the previous build.
++# 4. Rebuild with -fprofile-use.
+ all:
+ @if gcc-bootstrap
+ 	[ -f stage_final ] || echo stage3 > stage_final
+@@ -727,7 +772,7 @@ all:
+ 	$(MAKE) $(RECURSE_FLAGS_TO_PASS) `cat stage_final`-bubble
+ @endif gcc-bootstrap
+ 	@: $(MAKE); $(unstage)
+-	@r=`${PWD_COMMAND}`; export r; \
++	+@r=`${PWD_COMMAND}`; export r; \
+ 	s=`cd $(srcdir); ${PWD_COMMAND}`; export s; \
+ @if gcc-bootstrap
+ 	if [ -f stage_last ]; then \
+@@ -735,7 +780,16 @@ all:
+ 	  $(MAKE) $(TARGET_FLAGS_TO_PASS) all-host all-target; \
+ 	else \
+ @endif gcc-bootstrap
+-	  $(MAKE) $(RECURSE_FLAGS_TO_PASS) all-host all-target \
++	  $(MAKE) $(RECURSE_FLAGS_TO_PASS) \
++		$(PGO_BUILD_GEN_FLAGS_TO_PASS) all-host all-target \
++@if pgo-build
++	&& $(MAKE) $(RECURSE_FLAGS_TO_PASS) \
++		$(PGO_BUILD_TRAINING_FLAGS_TO_PASS) \
++		$(PGO_BUILD_TRAINING) \
++	&& $(MAKE) $(RECURSE_FLAGS_TO_PASS) clean \
++	&& $(MAKE) $(RECURSE_FLAGS_TO_PASS) \
++		$(PGO_BUILD_USE_FLAGS_TO_PASS) all-host all-target \
++@endif pgo-build
+ @if gcc-bootstrap
+ 	    ; \
+ 	fi \
